FinalTodo/Models/Todo.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace FinalTodo.Models
{
    public class Todo
    {
        public int Id { get; set; }
        public bool IsDone { get; set; }
        public string Description { get; set; }
        public virtual ApplicationUser User { get; set; }

        [DataType(DataType.Date)]
        public DateTime DueDate { get; set; }

        public string TimeUntil { get; set; }
    }
}

FinalTodo/Controllers/TodoesController.cs
using FinalTodo.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;


namespace FinalTodo.Controllers
{
    public class TodoesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Todoes
        public ActionResult Index()
        {

            return View();
        }

        private IEnumerable<Todo> GetMyTodoes()
        {
            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault
                (x => x.Id == currentUserId);
            IEnumerable<Todo> myTodoes = db.Todos.ToList().Where(x => x.User == currentUser);

            int CompletecCount = 0;
            foreach (Todo todo in myTodoes)
            {
                if (todo.IsDone)
                {
                    CompletecCount++;
                }
                TimeSpan TimeUntil = todo.DueDate.Subtract(DateTime.Now);
                string Formatted = "";
                if (todo.IsDone)
                {
                    Formatted = "Complete";
                }
                else if (TimeUntil.Days < 0)
                {
                    Formatted = (TimeUntil.Days * -1) + " Days Overdue";
                }
                else if (TimeUntil.Days > 0)
                {
                    Formatted = TimeUntil.Days + " Days until Due";
                }

                else
                {
                    Formatted = "Due Today";
                }
                todo.TimeUntil = Formatted;
            }
            ViewBag.Percent = Math.Round(100f * ((float)CompletecCount / (float)myTodoes.Count()));
            
            return myTodoes;
        }

        public ActionResult BuildTodoTable()
        {
            return PartialView("_TodoTable", GetMyTodoes());
        }

        // GET: Todoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Todo todo = db.Todos.Find(id);
            if (todo == null)
            {
                return HttpNotFound();
            }
            return View(todo);
        }

        // GET: Todoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Todoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,IsDone,Description,DueDate")] Todo todo)
        {
            if (ModelState.IsValid)
            {
                string currentUserId = User.Identity.GetUserId();
                ApplicationUser currentUser = db.Users.FirstOrDefault
                    (x => x.Id == currentUserId);
                todo.User = currentUser;

                TimeSpan TimeUntil = todo.DueDate.Subtract(DateTime.Now);
                string Formatted = "";
                if (TimeUntil.Days < 0)
                {
                    Formatted = (TimeUntil.Days * -1) + " Days Overdue";
                }
                else if (TimeUntil.Days > 0)
                {
                    Formatted = TimeUntil.Days + " Days until Due";
                }
                else
                {
                    Formatted = "Due Today";
                }
                todo.TimeUntil = Formatted;

                db.Todos.Add(todo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(todo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AJAXCreate([Bind(Include = "Id, Description,DueDate")] Todo todo)
        {
            if (ModelState.IsValid)
            {
                string currentUserId = User.Identity.GetUserId();
                ApplicationUser currentUser = db.Users.FirstOrDefault
                    (x => x.Id == currentUserId);
                todo.User = currentUser;

                TimeSpan TimeUntil = todo.DueDate.Subtract(DateTime.Now);
                string Formatted = "";
                if (TimeUntil.Days < 0)
                {
                    Formatted = (TimeUntil.Days * -1) + " Days Overdue";
                }
                else if (TimeUntil.Days > 0)
                {
                    Formatted = TimeUntil.Days + " Days until Due";
                }
                else
                {
                    Formatted = "Due Today";
                }
                todo.TimeUntil = Formatted;

                db.Todos.Add(todo);
                db.SaveChanges();
            }

            return PartialView("_TodoTable", GetMyTodoes());
        }

        // GET: Todoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Todo todo = db.Todos.Find(id);
            if (todo == null)
            {
                return HttpNotFound();
            }
            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault
                (x => x.Id == currentUserId);
            todo.User = currentUser;

            if (todo.User != currentUser)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(todo);
        }

        // POST: Todoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,IsDone,Description,DueDate")] Todo todo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(todo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(todo);
        }

        [HttpPost]
        public ActionResult AJAXEdit(int? id, bool value)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Todo todo = db.Todos.Find(id);
            if (todo == null)
            {
                return HttpNotFound();
            }
            else
            {
                todo.IsDone = value;
                db.Entry(todo).State = EntityState.Modified;
                db.SaveChanges();
                return PartialView("_TodoTable", GetMyTodoes());
            }
        }

        // GET: Todoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Todo todo = db.Todos.Find(id);
            if (todo == null)
            {
                return HttpNotFound();
            }
            return View(todo);
        }

        // POST: Todoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Todo todo = db.Todos.Find(id);
            db.Todos.Remove(todo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FinalTodo/Views/Todoes/Create.cshtml
@model FinalTodo.Models.Todo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Todo</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.IsDone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.IsDone)
                @Html.ValidationMessageFor(model => model.IsDone, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DueDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FinalTodo/Views/Todoes/Delete.cshtml
@model FinalTodo.Models.Todo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Todo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IsDone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>
        
        <dd>
            @Html.DisplayFor(model => model.DueDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FinalTodo/Views/Todoes/Details.cshtml
@model FinalTodo.Models.Todo

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Todo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IsDone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DueDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeUntil)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeUntil)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FinalTodo/Views/Todoes/Edit.cshtml
@model FinalTodo.Models.Todo

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Todo</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.IsDone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.IsDone)
                @Html.ValidationMessageFor(model => model.IsDone, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.DueDate)
            @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DueDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FinalTodo/Views/Todoes/Index.cshtml
@model FinalTodo.Models.Todo
@{
    ViewBag.Title = "Index";
}
<h1>My Todoes</h1>

<div id="tableDiv"></div>

<div id="todoCreateFrom">
    @using (Ajax.BeginForm("AJAXCreate", "Todoes", new AjaxOptions
    {
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "POST",
        UpdateTargetId = "tableDiv"
    }))
    {
    <div class="form-group">
        @Html.AntiForgeryToken()
        <div>
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>
    }
</div>

@section Scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/CustomScripts/BuildTable.js"></script>
    <script src="sorttable.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
    }

FinalTodo/Views/Todoes/_TodoTable.cshtml
@model IEnumerable<FinalTodo.Models.Todo>

    <div id="ProgressBarTodo">

        <div class="progress">
            @if ((ViewBag.Percent) != 100)
            {
                <div class="progress-bar" role="progressbar" 
                     style="width:@(Html.AttributeEncode(ViewBag.Percent))%"></div>
            }
            else
            {
                <div class="progress-bar CompletedProgressBar" role="progressbar" 
                     style="width:@(Html.AttributeEncode(ViewBag.Percent))%"></div>
            }

        </div>
        <p>@(ViewBag.Percent)% Complete</p>
    </div>
    <table id="todoTable" class="table">


        @foreach (var item in Model)
        {
            TimeSpan TimeUntil = item.DueDate.Subtract(DateTime.Now);
            if (TimeUntil.Days < 0 && !item.IsDone)
            {
        <tr>
            <td class="OverDueItem">
                @Html.CheckBoxFor(modelItem => item.IsDone,
                new { id = item.Id, @class = "ActiveCheck" })
            </td>
            <td class="OverDueItem">
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td class="OverDueItem">
                @Html.DisplayFor(modelItem => item.DueDate)
            </td>

            <td class="OverDueItem">
                @Html.DisplayFor(modelItem => item.TimeUntil)
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
            <td>
                <a href="#" class="up">Up</a>
                <a href="#" class="down">Down</a>
                <a href="#" class="top">Top</a>
                <a href="#" class="bottom">Bottom</a>
            </td>
        </tr>
            }
            else
            {
    <tr>
        <td>
            @Html.CheckBoxFor(modelItem => item.IsDone,
            new { id = item.Id, @class = "ActiveCheck" })
        </td>
        <td>
            @if (!item.IsDone)
            {
                @Html.DisplayFor(modelItem => item.Description)
            }
            else
            {
                <div class="CompletedTodo">@Html.DisplayFor(modelItem => item.Description)</div>
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DueDate)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.TimeUntil)
        </td>

         <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
         </td>
    
         <td>
            <a href="#" class="up">Up</a>
            <a href="#" class="down">Down</a>
            <a href="#" class="top">Top</a>
            <a href="#" class="bottom">Bottom</a>
         </td>
    </tr>
            }
        }

    </table>

<script src="~/CustomScripts/AddCheckBoxListeners.js"></script>
<script src="~/CustomScripts/TableSort.js"></script>